OJ-39182 Mark custom field issue mismatches for redownload
Jellyfish-AI/jf_agent pull request #365
Opened 2024-10-15 18:39 UTC by ashleyredzko

This uses the `mark_for_redownload` kwarg in `identify_custom_field_mismatches` to send mismatched custom field issues to Jellyfish to redownload them.

2024-10-15 19:04 UTC, lheureuxe13 commented on jf_agent/jf_jira/jira_download.py
> +    logger.info(f'Beginning detection of custom field mismatches. Submit issues for redownload: {submit_issues_for_repair}')
Nit: could you run `pdm run black jf_agent/jf_jira/jira_download.py` to reformat a few long lines of code in this change?

2024-10-15 19:10 UTC, lheureuxe13 reviewed
Same question as Jack on your other PR re: logging in jf_ingest, otherwise LGTM

2024-10-15 20:03 UTC, ashleyredzko commented on jf_agent/jf_jira/jira_download.py
> +        logger.info(f'{len(all_ids)} issue IDs submitted to Jellyfish for redownload')
TODO: If https://github.com/Jellyfish-AI/jf_ingest/pull/192 is pulled into this PR, this is redundant and can be removed.

2024-10-15 20:46 UTC, ashleyredzko commented on jf_agent/jf_jira/jira_download.py
> -                logger.info('No Jira Issues were marked as needing their custom fields repaired')
This logging is either redundant or completely ported over to `jf_ingest`.

2024-10-15 20:47 UTC, ashleyredzko commented on jf_agent/jf_jira/jira_download.py
> -        )
All of the above logging is now present in `jf_ingest` version `0.0.138`, and is redundant here.

2024-10-15 20:52 UTC, lheureuxe13 approved these changes
Might want to wait until the morning to merge so that we can monitor more closely, otherwise LGTM 🫡

2024-10-15 21:00 UTC, jruel4 commented
> Might want to wait until the morning to merge so that we can monitor more closely, otherwise LGTM 🫡

+1 otherwise LGTM

2024-10-15 21:03 UTC, jruel4 requested changes
Couple of things

2024-10-15 21:04 UTC, jruel4 commented on pdm.lock
> -version = "2023.7.22"
Q: Any way to do targeted update of only `jf_ingest`? Maybe I'm misremembering, but this feels like more changes than usual.

2024-10-15 21:07 UTC, jruel4 commented on jf_agent/jf_jira/jira_download.py
> -            ids_to_redownload = detect_and_repair_custom_fields(ingest_config=ingest_config)
B: This functionality needs to be retained. We only get the issue IDs to redownload at the beginning (whenever we initially generate `IngestionConfig`). Without this functionality, we won't pick up issues that are marked for redownload until the next agent run.

2024-10-16 15:53 UTC, jruel4 approved these changes
Excellent, thank you!

2024-10-16 15:54 UTC, merged